# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-01 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_Category',
            new_name='image_category',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_Description',
            new_name='image_description',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_Location',
            new_name='image_location',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_Name',
            new_name='image_name',
        ),
    ]
